version: '3.1'

services:
  db:
    depends_on:
      - bot_db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  bot_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${BOT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BOT_DB_PASSWORD}
      POSTGRES_DB: 'bot_db'
    ports:
      - '7514:3306'
    expose:
      - '3306'