version: '3.8'

services:
  db:
    depends_on:
      - bot-db
    build:
      context: .
    restart: always
  bot-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-db
    ports:
      - '7514:5432'
    expose:
      - '7514'
